import AppKit
import Foundation

nonisolated protocol HistoryServing: Sendable {
    func items() async -> [HistoryItem]
    func search(_ query: String) async -> [HistoryItem]
    func ingest(_ snapshot: PasteboardSnapshot) async
    func delete(id: UUID) async
    func sweepExpired(olderThan: Date) async
}

nonisolated struct HistoryItem: Identifiable, Sendable, Hashable, Codable {
    let id: UUID
    let createdAt: Date
    let plainText: String
    let sourceBundleID: String?
    let hasImage: Bool
    let hasFilePromise: Bool
    let types: [String]
    let payloads: [String: Data]

    init(
        id: UUID,
        createdAt: Date,
        plainText: String,
        sourceBundleID: String?,
        hasImage: Bool,
        hasFilePromise: Bool = false,
        types: [String] = [],
        payloads: [String: Data] = [:]
    ) {
        self.id = id
        self.createdAt = createdAt
        self.plainText = plainText
        self.sourceBundleID = sourceBundleID
        self.hasImage = hasImage
        self.hasFilePromise = hasFilePromise
        self.types = types
        self.payloads = payloads
    }

    /// 用来判断「用户眼里是不是同一条」。忽略来源应用和会随每次复制变掉的元数据。
    var contentIdentity: ClipboardContentIdentity {
        if hasImage, let image = imageBytes() {
            return .image(image)
        }
        if let file = fileURLString() {
            return .file(file)
        }
        if !plainText.isEmpty {
            return .text(plainText)
        }
        return .payloads(stablePayloads())
    }

    func imageBytes() -> Data? {
        let preferred = [
            "public.png",
            "public.jpeg",
            "public.jpg",
            "public.tiff",
            "public.heic",
            "public.gif",
            "public.image"
        ]
        for type in preferred {
            if let data = payloads[type], !data.isEmpty {
                return data
            }
        }
        for (type, data) in payloads where PasteboardCapture.isImageType(type) && !data.isEmpty {
            return data
        }
        return nil
    }

    private func fileURLString() -> String? {
        guard let data = payloads["public.file-url"],
              let raw = String(data: data, encoding: .utf8)
        else {
            return nil
        }
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    private func stablePayloads() -> [String: Data] {
        let ignored: Set<String> = [
            PasteboardCapture.internalType,
            PasteboardCapture.concealedType,
            PasteboardCapture.transientType,
            PasteboardCapture.autoGeneratedType,
            "com.apple.pasteboard.promised-file-url",
            "com.apple.pasteboard.promised-file-content",
            "org.chromium.source-url",
            "org.chromium.source-frame-url",
            "com.apple.traditional-mac-plain-text"
        ]
        return payloads.filter { key, value in
            !value.isEmpty
                && !ignored.contains(key)
                && !key.hasPrefix("dyn.")
                && !key.lowercased().contains("webkit")
                && !key.lowercased().contains("chromium")
        }
    }
}

nonisolated enum ClipboardContentIdentity: Hashable, Sendable {
    case image(Data)
    case file(String)
    case text(String)
    case payloads([String: Data])
}

nonisolated struct PasteboardSnapshot: Sendable {
    let changeCount: Int
    let types: [String]
    let payloads: [String: Data]
    let sourceBundleID: String?
    let hasFilePromise: Bool

    init(
        changeCount: Int,
        types: [String],
        payloads: [String: Data],
        sourceBundleID: String?,
        hasFilePromise: Bool = false
    ) {
        self.changeCount = changeCount
        self.types = types
        self.payloads = payloads
        self.sourceBundleID = sourceBundleID
        self.hasFilePromise = hasFilePromise
    }

    func makeHistoryItem(id: UUID = UUID(), createdAt: Date = Date()) -> HistoryItem {
        HistoryItem(
            id: id,
            createdAt: createdAt,
            plainText: HistoryText.plainText(from: payloads),
            sourceBundleID: sourceBundleID,
            hasImage: types.contains(where: PasteboardCapture.isImageType),
            hasFilePromise: hasFilePromise,
            types: types,
            payloads: payloads
        )
    }
}

nonisolated enum HistorySearch: Sendable {
    nonisolated static func matches(_ item: HistoryItem, query: String) -> Bool {
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return true }
        return item.plainText.localizedCaseInsensitiveContains(trimmed)
    }
}

nonisolated enum HistoryText: Sendable {
    nonisolated static func plainText(from payloads: [String: Data]) -> String {
        let utf8Keys = [
            "public.utf8-plain-text",
            "NSStringPboardType",
            "public.plain-text"
        ]
        for key in utf8Keys {
            if let data = payloads[key], let text = String(data: data, encoding: .utf8), !text.isEmpty {
                return text
            }
        }
        if let data = payloads["public.utf16-plain-text"],
           let text = String(data: data, encoding: .utf16), !text.isEmpty {
            return text
        }
        if let data = payloads["public.rtf"],
           let attributed = NSAttributedString(rtf: data, documentAttributes: nil) {
            let text = attributed.string
            if !text.isEmpty { return text }
        }
        if let data = payloads["public.html"],
           let attributed = NSAttributedString(html: data, documentAttributes: nil) {
            let text = attributed.string
            if !text.isEmpty { return text }
        }
        if let data = payloads["public.file-url"],
           let raw = String(data: data, encoding: .utf8),
           let url = URL(string: raw.trimmingCharacters(in: .whitespacesAndNewlines)) {
            return url.lastPathComponent
        }
        return ""
    }

    /// 列表上给人看的标题。图片若只有系统临时文件名，就显示「图片」，不要把内部编号亮出来。
    static func listTitle(plainText: String, hasImage: Bool) -> String {
        let trimmed = plainText.trimmingCharacters(in: .whitespacesAndNewlines)
        if hasImage, trimmed.isEmpty || isMachineGeneratedName(trimmed) {
            return String(localized: "panel.image.placeholder")
        }
        return trimmed
    }

    static func isMachineGeneratedName(_ text: String) -> Bool {
        let name = basename(of: text)
        guard !name.isEmpty else { return false }
        let stem = (name as NSString).deletingPathExtension
        let pattern = #"^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}([_-][0-9A-Za-z]+)*$"#
        return stem.range(of: pattern, options: .regularExpression) != nil
    }

    private static func basename(of text: String) -> String {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if let url = URL(string: trimmed), url.scheme == "file" {
            return url.lastPathComponent
        }
        if trimmed.contains("/") {
            return URL(fileURLWithPath: trimmed).lastPathComponent
        }
        return trimmed
    }
}
