import AppKit
import Foundation

/// 从系统剪贴板组装快照。先看类型标记再读字节；密码管理器与瞬时内容直接丢弃。
nonisolated enum PasteboardCapture: Sendable {
    /// 本应用写回历史条目时打上的标记，避免自己的粘贴再被收录成一条新历史。
    nonisolated static let internalType = "com.x0c.NeatPaste.internal"
    nonisolated static let concealedType = "org.nspasteboard.ConcealedType"
    nonisolated static let transientType = "org.nspasteboard.TransientType"
    nonisolated static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"
    nonisolated static let microsoftLinkSource = "com.microsoft.Link-Source"
    nonisolated static let microsoftObjectLink = "com.microsoft.Object-Link"
    nonisolated static let microsoftSourcePrefix = "com.microsoft.ole.source."

    nonisolated static let promisedFileTypes: Set<String> = [
        "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-file-content",
        "NSFilesPromisePboardType",
        "com.apple.NSPromiseContentsPboardType"
    ]

    nonisolated static let extraSensitiveTypes: Set<String> = [
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb"
    ]

    enum Decision: Equatable, Sendable {
        case skipSensitive
        case skipOwnWrite
        case skipIgnoredApp
        case capture
    }

    /// 纯函数：只根据类型列表和来源应用决定收不收，方便单测。
    nonisolated static func decide(types: [String], sourceBundleID: String?, ignoredApps: [String]) -> Decision {
        let set = Set(types)
        if set.contains(internalType) {
            return .skipOwnWrite
        }
        if set.contains(concealedType)
            || set.contains(transientType)
            || set.contains(autoGeneratedType)
            || !set.isDisjoint(with: extraSensitiveTypes) {
            return .skipSensitive
        }
        if let sourceBundleID, ignoredApps.contains(sourceBundleID) {
            return .skipIgnoredApp
        }
        return .capture
    }

    nonisolated static func isUnsafeToRead(_ type: String) -> Bool {
        type == microsoftLinkSource
            || type == microsoftObjectLink
            || type.hasPrefix(microsoftSourcePrefix)
    }

    nonisolated static func isFilePromise(_ type: String) -> Bool {
        promisedFileTypes.contains(type)
    }

    nonisolated static func isImageType(_ type: String) -> Bool {
        let lowered = type.lowercased()
        return lowered.contains("png")
            || lowered.contains("tiff")
            || lowered.contains("jpeg")
            || lowered.contains("jpg")
            || lowered.contains("heic")
            || lowered.contains("heif")
            || lowered.contains("gif")
            || lowered == "public.image"
    }

    /// 在主线程读剪贴板。先看类型，再读条目字节；条目为空则回退到整板字符串/数据。
    /// OLE 链接源和文件承诺只记类型不读字节。
    @MainActor
    static func snapshot(
        from pasteboard: NSPasteboard,
        sourceBundleID: String?,
        ignoredApps: [String]
    ) -> PasteboardSnapshot? {
        let advertised = pasteboard.types?.map(\.rawValue) ?? []
        switch decide(types: advertised, sourceBundleID: sourceBundleID, ignoredApps: ignoredApps) {
        case .skipSensitive, .skipOwnWrite, .skipIgnoredApp:
            return nil
        case .capture:
            break
        }

        var orderedTypes: [String] = []
        var payloads: [String: Data] = [:]
        var hasFilePromise = false

        let items = pasteboard.pasteboardItems ?? []
        var typeQueue: [String] = []
        for item in items {
            for type in item.types where !typeQueue.contains(type.rawValue) {
                typeQueue.append(type.rawValue)
            }
        }
        for raw in advertised where !typeQueue.contains(raw) {
            typeQueue.append(raw)
        }

        for raw in typeQueue {
            if isUnsafeToRead(raw) {
                continue
            }
            if isFilePromise(raw) {
                hasFilePromise = true
                if !orderedTypes.contains(raw) {
                    orderedTypes.append(raw)
                }
                continue
            }
            if payloads[raw] != nil {
                continue
            }
            let pasteType = NSPasteboard.PasteboardType(raw)
            guard let data = readPayload(pasteType, from: items, pasteboard: pasteboard) else {
                continue
            }
            orderedTypes.append(raw)
            payloads[raw] = data
        }

        if payloads.isEmpty, !hasFilePromise {
            return nil
        }

        return PasteboardSnapshot(
            changeCount: pasteboard.changeCount,
            types: orderedTypes,
            payloads: payloads,
            sourceBundleID: sourceBundleID,
            hasFilePromise: hasFilePromise
        )
    }

    /// 变化已看见但内容还没装上时不要把计数往前推，下次探测或打开面板还能再试。
    /// 密码/瞬时/本应用写回则算处理完，避免反复读敏感内容。
    nonisolated static func shouldAdvanceChangeCount(decision: Decision, didCapture: Bool) -> Bool {
        switch decision {
        case .skipSensitive, .skipOwnWrite, .skipIgnoredApp:
            return true
        case .capture:
            return didCapture
        }
    }

    @MainActor
    private static func readPayload(
        _ type: NSPasteboard.PasteboardType,
        from items: [NSPasteboardItem],
        pasteboard: NSPasteboard
    ) -> Data? {
        for item in items {
            if let data = item.data(forType: type), !data.isEmpty {
                return data
            }
            if let string = item.string(forType: type), !string.isEmpty,
               let data = string.data(using: .utf8), !data.isEmpty {
                return data
            }
        }
        if let data = pasteboard.data(forType: type), !data.isEmpty {
            return data
        }
        if let string = pasteboard.string(forType: type), !string.isEmpty,
           let data = string.data(using: .utf8), !data.isEmpty {
            return data
        }
        return nil
    }
}
